### PR TITLE
Fix detection of the ck-generic- kernel variants

### LINKED ISSUE #136: Doesn't work with ck-generic-v3 kernel
I'm using the `linux-ck-generic-v3` package and kernel

My `uname -r` gives me back `6.4.1-2-ck-generic-v3`

```sh
reboot-arch-btw 
Kernel
 installed: 6.4.1.arch2-1 (since 2 days ago)
 running:   6.4.1.2.ck.generic.v3
Reboot arch btw
```

Looks like it's comparing against the `linux` package, if that is removed I get `[2023-07-07T13:00:36Z ERROR reboot_arch_btw] Could not create kernel checker: Could not get version of installed kernel: could not find or read package`

### PR DESCRIPTION
**Pull request by rnestler**
Fixes #136

### CODE REVIEW

**Comment by rnestler** [comment]
@Sacro Can you test this and verify that it works for you?

**Comment by Sacro** [comment]
I'l need to reboot into the CK kernel, it's currently broken for -zen too though!

```
Kernel
 installed: 6.4.6.zen1-1 (since 26 hours ago)
 running:   6.4.6.zen1.1-zen
```

**Comment by rnestler** [comment]
> I'l need to reboot into the CK kernel, it's currently broken for -zen too though!

Why? The output looks sane, doesn't it? Or what is your current `uname -r` and `pacman -Q linux-zen` output?

**Comment by Sacro** [comment]
Oh sorry, yes it does look sane, Just that running has `-zen` suffixed, that threw me.

**Comment by rnestler** [comment]
> Oh sorry, yes it does look sane, Just that running has -zen suffixed, that threw me.

Yeah that's the confusing thing: `uname -r` will report something like `6.4.6.zen1.1-zen` (with some dots replaced by `-`) which then means it's the `linux-zen` package with the version `6.4.6.zen1-1` (again some `.` are actually `-` and vice versa).

So in the code we normalize these before comparing them, but the output is the original package version, but a normalized `uname -r` output. Definitely confusing :wink: 

I added some more info messages in #138 which should help debug these issues. Just set `RUST_LOG=info` to see them:
```
$ RUST_LOG=info target/debug/reboot-arch-btw
[2023-07-27T08:26:59Z INFO  reboot_arch_btw::kernel] uname -r output: 6.4.4-arch1-1
[2023-07-27T08:26:59Z INFO  reboot_arch_btw::kernel] Detected kernel package: linux
[2023-07-27T08:26:59Z INFO  reboot_arch_btw::kernel] kernel package version: 6.4.6.arch1-1
Kernel
 installed: 6.4.6.arch1-1 (since 53 minutes ago)
 running:   6.4.4.arch1.1
[2023-07-27T08:26:59Z INFO  reboot_arch_btw::critical_packages_check] Checking systemd
systemd updated 2 days ago
Reboot arch btw

**Comment by Sacro** [comment]
```
[2023-07-27T10:09:05Z INFO  reboot_arch_btw::kernel] uname -r output: 6.4.6-zen1-1-zen
[2023-07-27T10:09:05Z INFO  reboot_arch_btw::kernel] Detected kernel package: linux-zen
[2023-07-27T10:09:05Z INFO  reboot_arch_btw::kernel] kernel package version: 6.4.6.zen1-1
Kernel
 installed: 6.4.6.zen1-1 (since 1 days ago)
 running:   6.4.6.zen1.1-zen
[2023-07-27T10:09:05Z INFO  reboot_arch_btw::critical_packages_check] Checking systemd
[2023-07-27T10:09:05Z INFO  reboot_arch_btw::critical_packages_check] Checking linux-firmware
[2023-07-27T10:09:05Z INFO  reboot_arch_btw::critical_packages_check] Checking amd-ucode
[2023-07-27T10:09:05Z INFO  reboot_arch_btw::critical_packages_check] Checking intel-ucode
[2023-07-27T10:09:05Z WARN  reboot_arch_btw::critical_packages_check] Failed to get package info for intel-ucode
[2023-07-27T10:09:05Z INFO  reboot_arch_btw::critical_packages_check] Checking xorg-server
[2023-07-27T10:09:05Z INFO  reboot_arch_btw::critical_packages_check] Checking xorg-xwayland
```

**Comment by rnestler** [comment]
Thanks looks nice. If you find time to test it with CK kernel it would be appreciated. But if not, I'd just merge it and you could still reopen the issue if problems persist :slightly_smiling_face:

**Comment by rnestler** [comment]
(Regarding `[2023-07-27T10:09:05Z WARN  reboot_arch_btw::critical_packages_check] Failed to get package info for intel-ucode`: You could explicitly pass `--reboot-packages` with a list of packages you want to have checked.)

**Comment by Sacro** [comment]
Yeah, I've rebooted for you, though I have OS lockups on 6.4.3 for some reason.

```
[2023-07-27T12:20:23Z INFO  reboot_arch_btw::kernel] uname -r output: 6.4.3-1-ck-generic-v3
[2023-07-27T12:20:23Z INFO  reboot_arch_btw::kernel] Detected kernel package: linux-ck-generic-v3
[2023-07-27T12:20:23Z INFO  reboot_arch_btw::kernel] kernel package version: 6.4.3-1
Kernel
 installed: 6.4.3-1 (since 14 days ago)
 running:   6.4.3.1-ck-generic-v3
[2023-07-27T12:20:23Z INFO  reboot_arch_btw::critical_packages_check] Checking systemd
[2023-07-27T12:20:23Z INFO  reboot_arch_btw::critical_packages_check] Checking linux-firmware
[2023-07-27T12:20:23Z INFO  reboot_arch_btw::critical_packages_check] Checking amd-ucode
[2023-07-27T12:20:23Z INFO  reboot_arch_btw::critical_packages_check] Checking intel-ucode
[2023-07-27T12:20:23Z WARN  reboot_arch_btw::critical_packages_check] Failed to get package info for intel-ucode
[2023-07-27T12:20:23Z INFO  reboot_arch_btw::critical_packages_check] Checking xorg-server
[2023-07-27T12:20:23Z INFO  reboot_arch_btw::critical_packages_check] Checking xorg-xwayland
```

**Comment by rnestler** [comment]
Nice! Seems to work as expected :tada: 

Thanks for testing!

**Pull request merged**
