### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by rnestler**

### CODE REVIEW

**Comment by Morganamilo** [comment]
> Update dependencies to latest semver compatible

alpm v2 is required to work with the new pacman so just bumping it to 1.1.14 won't work.

**Comment by rnestler** [comment]
>  alpm v2 is required to work with the new pacman so just bumping it to 1.1.14 won't work.

Huh. Funny enough it still works on my system. How is this possible?

**Comment by rnestler** [comment]
(But `yay` is broken due to the update)

**Comment by Morganamilo** [comment]
> Huh. Funny enough it still works on my system. How is this possible?

Either you've not got the new pacman installed. Or you're still using alpm v1.1.7 which predates the version check.

**Comment by rnestler** [comment]
> Either you've not got the new pacman installed. Or you're still using alpm v1.1.7 which predates the version check.

After a `cargo clean` it now fails to build :laughing: I probalby built with alpm v1.1.9 while still on pacman 5 and then the dependencies never got rebuilt.

**Pull request merged**
