### PR TITLE
Add support for non default kernels

### LINKED ISSUE #3: Support non default kernels btw.
Arch has more than one supported kernel (linux-lts for example). Currently kernel-updated checks only if the package linux got updated.

### PR DESCRIPTION
**Pull request by rnestler**
Fixes #3

### CODE REVIEW

**Comment by rnestler** [comment]
@dbrgn Care to take a look?

@CobaltSpace Could you test this code on your system?

**Comment by CobaltSpace** [comment]
```
$ ./reboot-arch-btw
Kernel
 installed: 5.6.13.zen1-1 (since 1 days ago)
 running:   5.6.13-zen1-1
You should reboot arch btw!
Xorg server
 installed: 1.20.8-2 (since 11 days ago)
 running:   1.20.8
```

**Comment by rnestler** [comment]
> There is a punctuation mismatch between the installed and running kernel (running uses a `-` where installed uses a `.`)

Oh indeed. Should be easy to fix if we just normalize the output to replace every `-` with a `.`.

**Comment by rnestler** [comment]
@CobaltSpace Can you test again?

**Comment by rnestler** [comment]
@CobaltSpace I'll merge this for now. It doesn't break the detection of the default kernel version and should fix it for alternative kernels. Please fill an issue if it doesn't work for you :slightly_smiling_face:

**Pull request merged**
